litellm_params:
  model: gemini/gemini-1.5-pro

model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek-chat
      api_key: "os.environ/DEEPSEEK_API_KEY"
  - model_name: mercury-coder
    litellm_params:
      model: mercury-coder-small
      api_base: "https://api.inceptionlabs.ai/v1" # Custom API base URL
      api_key: "os.environ/MERCURY_TOKEN" # OPENAI_TOKEN env var
  - model_name: gemini-pro
    litellm_params:
      model: gemini-pro
      api_key: "os.environ/GOOGLE_API_KEY"
  - model_name: grok-ai
    litellm_params:
      model: grok-chat
      api_key: "os.environ/GROK_API_KEY"
  - model_name: gpt-4.1-nano
    litellm_params:
      model: gpt-4.1-nano
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: claude-sonnet-3.7
    litellm_params:
      model: claude-sonnet-3.7
      api_key: "os.environ/ANTHROPIC_API_KEY"
